import {
  TruckItem,
  ShipmentItem,
  RiskFactor,
  JourneyStage,
  AlertItem,
  VerificationRecord,
  ConnectionNode,
  TelemetryPoint,
  RelayNode,
  MapTruckNode,
} from '@/types/telemetry';

export const mockFleetStats = {
  activeTrucks: 18,
  offlineTrucks: 3, // MUST BE RED
  activeShipments: 24,
  highRiskShipments: 3,
  averageShelfLife: '6.8 days',
  totalTrucks: 32,
  onlineTrucks: 27,
  needsAttentionTrucks: 2,
};

export const mockWholesalerStats = {
  arrivingToday: 8,
  inTransit: 5,
  highRisk: 2,
  averageShelfLife: '5.9 days',
};

export const mockTrucks: TruckItem[] = [
  {
    id: 'TRK-104',
    driver: 'Rajesh Verma',
    route: 'Nashik → Nagpur → Raipur',
    shipmentId: 'SH-1024',
    cargoName: 'Fresh Apples',
    temperature: '5.2°C',
    battery: 84,
    connectionStatus: 'Internet connected',
    spoilageRisk: 23,
    status: 'Online',
    lastSeen: '48 seconds ago',
    remainingShelfLife: '6.4 days',
    xPercent: 28,
    yPercent: 62,
  },
  {
    id: 'TRK-108',
    driver: 'Amit Sharma',
    route: 'Pune → Solapur → Hyderabad',
    shipmentId: 'SH-1031',
    cargoName: 'Organic Tomatoes',
    temperature: '8.7°C',
    battery: 65,
    connectionStatus: 'Internet connected',
    spoilageRisk: 67,
    status: 'Needs Attention',
    lastSeen: '2 minutes ago',
    remainingShelfLife: '2.8 days',
    xPercent: 44,
    yPercent: 54,
  },
  {
    id: 'TRK-112',
    driver: 'Suresh Kumar',
    route: 'Nagpur → Raipur Bypass',
    shipmentId: 'SH-1042',
    cargoName: 'Export Grade Mangoes',
    temperature: '7.8°C',
    battery: 42,
    connectionStatus: 'Internet unavailable (Offline storing)',
    spoilageRisk: 64,
    status: 'Offline', // MUST BE RED
    lastSeen: '18 minutes ago',
    remainingShelfLife: '4.2 days',
    xPercent: 56,
    yPercent: 46,
  },
  {
    id: 'TRK-119',
    driver: 'Vikram Singh',
    route: 'Mahabaleshwar → Mumbai',
    shipmentId: 'SH-1055',
    cargoName: 'Fresh Strawberries',
    temperature: '2.1°C',
    battery: 92,
    connectionStatus: 'Long-range relay active',
    spoilageRisk: 12,
    status: 'Online',
    lastSeen: '1 minute ago',
    remainingShelfLife: '4.8 days',
    xPercent: 66,
    yPercent: 38,
  },
  {
    id: 'TRK-115',
    driver: 'Dinesh Patel',
    route: 'Indore → Bhopal',
    shipmentId: 'SH-1060',
    cargoName: 'Dairy Packs',
    temperature: '6.9°C',
    battery: 78,
    connectionStatus: 'Internet connected',
    spoilageRisk: 45,
    status: 'Needs Attention',
    lastSeen: '5 minutes ago',
    remainingShelfLife: '5.1 days',
    xPercent: 38,
    yPercent: 30,
  },
  {
    id: 'TRK-122',
    driver: 'Ramesh Yadav',
    route: 'Jabalpur → Bilaspur',
    shipmentId: 'SH-1077',
    cargoName: 'Citrus Oranges',
    temperature: '9.1°C',
    battery: 15,
    connectionStatus: 'Internet unavailable (Offline storing)',
    spoilageRisk: 78,
    status: 'Offline',
    lastSeen: '34 minutes ago',
    remainingShelfLife: '2.1 days',
    xPercent: 72,
    yPercent: 28,
  },
  {
    id: 'TRK-130',
    driver: 'Manoj Tiwari',
    route: 'Surat → Ahmedabad',
    shipmentId: 'SH-1089',
    cargoName: 'Green Grapes',
    temperature: '8.2°C',
    battery: 28,
    connectionStatus: 'Internet unavailable (Offline storing)',
    spoilageRisk: 82,
    status: 'Offline',
    lastSeen: '52 minutes ago',
    remainingShelfLife: '1.9 days',
    xPercent: 18,
    yPercent: 42,
  },
];

export const mockShipments: ShipmentItem[] = [
  {
    id: 'SH-1024',
    product: 'Fresh Apples',
    volume: '2,400 kg (12 Pallets)',
    truckId: 'TRK-104',
    origin: 'Nashik Farm Hub',
    destination: 'Raipur Regional Warehouse',
    eta: '4:30 PM (In 14 mins)',
    temperature: '5.2°C',
    temperatureStatus: 'Normal',
    humidity: '72%',
    ethylene: '0.31 ppm',
    remainingShelfLife: '6.4 days',
    spoilageRisk: 23,
    riskLevel: 'Low',
    status: 'Arriving Soon',
    battery: 84,
    connectionStatus: 'Online',
    verifiedRecord: true,
    decisionRecommendation: 'SAFE TO RECEIVE',
  },
  {
    id: 'SH-1055',
    product: 'Fresh Strawberries',
    volume: '800 kg (4 Pallets)',
    truckId: 'TRK-119',
    origin: 'Mahabaleshwar Farm',
    destination: 'Raipur Regional Warehouse',
    eta: '5:15 PM (In 1h 00m)',
    temperature: '2.1°C',
    temperatureStatus: 'Normal',
    humidity: '85%',
    ethylene: '0.15 ppm',
    remainingShelfLife: '4.8 days',
    spoilageRisk: 12,
    riskLevel: 'Low',
    status: 'In Transit',
    battery: 92,
    connectionStatus: 'Long-range relay',
    verifiedRecord: true,
    decisionRecommendation: 'SAFE TO RECEIVE',
  },
  {
    id: 'SH-1031',
    product: 'Organic Tomatoes',
    volume: '3,200 kg (16 Pallets)',
    truckId: 'TRK-108',
    origin: 'Solapur Farm Hub',
    destination: 'Raipur Regional Warehouse',
    eta: '6:10 PM (In 1h 55m)',
    temperature: '8.7°C',
    temperatureStatus: 'Warning',
    humidity: '68%',
    ethylene: '0.48 ppm',
    remainingShelfLife: '2.8 days',
    spoilageRisk: 67,
    riskLevel: 'High',
    status: 'In Transit',
    battery: 65,
    connectionStatus: 'Online',
    verifiedRecord: true,
    decisionRecommendation: 'REVIEW BEFORE RECEIVING',
  },
  {
    id: 'SH-1042',
    product: 'Export Grade Mangoes',
    volume: '1,800 kg (9 Pallets)',
    truckId: 'TRK-112',
    origin: 'Ratnagiri Orchard',
    destination: 'Raipur Regional Warehouse',
    eta: 'Tomorrow 8:00 AM',
    temperature: '7.8°C',
    temperatureStatus: 'Excursion',
    humidity: '74%',
    ethylene: '0.55 ppm',
    remainingShelfLife: '4.2 days',
    spoilageRisk: 64,
    riskLevel: 'High',
    status: 'Delayed',
    battery: 42,
    connectionStatus: 'Offline storing',
    verifiedRecord: true,
    decisionRecommendation: 'REVIEW BEFORE RECEIVING',
  },
];

export const mockTelemetryStream: TelemetryPoint[] = [
  { time: '08:00 AM (Pickup)', cargoTemp: 3.8, safeUpper: 6.0, safeLower: 3.0, humidity: 72, ethylenePpm: 0.18 },
  { time: '09:00 AM', cargoTemp: 3.7, safeUpper: 6.0, safeLower: 3.0, humidity: 72, ethylenePpm: 0.20 },
  { time: '10:00 AM', cargoTemp: 3.6, safeUpper: 6.0, safeLower: 3.0, humidity: 72, ethylenePpm: 0.22 },
  { time: '11:00 AM', cargoTemp: 3.8, safeUpper: 6.0, safeLower: 3.0, humidity: 72, ethylenePpm: 0.23 },
  { time: '12:00 PM', cargoTemp: 4.2, safeUpper: 6.0, safeLower: 3.0, humidity: 72, ethylenePpm: 0.25 },
  { 
    time: '12:45 PM Defrost', 
    cargoTemp: 7.2, 
    safeUpper: 6.0, 
    safeLower: 3.0, 
    isExcursion: true, 
    excursionInfo: '⚠️ 12:45 PM Defrost Excursion\nPeaked at 7.2°C (25m duration) during automatic cycle. Cargo normalized to 5.2°C at 01:10 PM.', 
    humidity: 72, 
    ethylenePpm: 0.27 
  },
  { time: '01:10 PM', cargoTemp: 5.2, safeUpper: 6.0, safeLower: 3.0, humidity: 72, ethylenePpm: 0.28 },
  { time: '02:00 PM', cargoTemp: 5.2, safeUpper: 6.0, safeLower: 3.0, humidity: 72, ethylenePpm: 0.29 },
  { time: '03:00 PM', cargoTemp: 5.2, safeUpper: 6.0, safeLower: 3.0, humidity: 72, ethylenePpm: 0.30 },
  { time: '04:30 PM (ETA Dest.)', cargoTemp: 5.2, safeUpper: 6.0, safeLower: 3.0, humidity: 72, ethylenePpm: 0.31 },
];

export const mockRelayNodes: RelayNode[] = [
  {
    id: 'Node A',
    tag: 'Node A (Cell Blindspot)',
    truckId: 'TRK-112 (Nagpur Bypass)',
    role: 'Cell Blindspot',
    description: 'Cellular network unavailable. Automatically saving local sensor readings for upload (hop-distance: 2.1km).',
    statusBadge: 'Buffer: 14 Telemetry Packets',
    statusType: 'error',
    icon: 'cell',
  },
  {
    id: 'Node B',
    tag: 'Node B (Relay Carrier)',
    truckId: 'TRK-119 (Active Gateway)',
    role: 'Relay Carrier',
    description: 'Inbound packet ingestion from TRK-112 verified via hash digest. Multiplexing onto outbound 4G pipe.',
    statusBadge: 'Relay RSSI: -92 dBm (Strong)',
    statusType: 'primary',
    icon: 'wifi',
  },
  {
    id: 'Node C',
    tag: 'Node C (Cloud Core)',
    truckId: 'FreshTrace AI Cloud',
    role: 'Cloud Core',
    description: 'Zero-loss reconciliation of time-series thermal log. Ledger timestamp preserved at ingestion point.',
    statusBadge: 'Zero Data Loss Assured',
    statusType: 'success',
    icon: 'cloud',
  },
];

export const mockMapTrucks: MapTruckNode[] = [
  {
    id: 'm1',
    truckId: 'TRK-104',
    name: 'TRK-104 • 4.8°C',
    locationName: 'Nashik Hub',
    temp: '4.8°C',
    status: 'Normal',
    xPercent: 28,
    yPercent: 62,
    shipmentId: 'SH-1024',
    cargoName: 'Kashmir Apples',
  },
  {
    id: 'm2',
    truckId: 'TRK-108',
    name: 'TRK-108 • 8.7°C ⚠️',
    locationName: 'Pune Cold Terminal',
    temp: '8.7°C',
    status: 'Warning',
    xPercent: 44,
    yPercent: 54,
    shipmentId: 'SH-1031',
    cargoName: 'Organic Vine Tomatoes',
  },
  {
    id: 'm3',
    truckId: 'TRK-112',
    name: 'TRK-112 - OFFLINE (18m)',
    locationName: 'Nagpur Bypass',
    temp: '7.8°C',
    status: 'Critical',
    xPercent: 56,
    yPercent: 46,
    lastSeen: '18 min ago',
    shelfLife: '4.2 Days',
    spoilageRisk: '64%',
    loraRelayInfo: 'Relaying packets through nearby TRK-119. Store & forward buffer: 14 cached records.',
    shipmentId: 'SH-1042',
    cargoName: 'Alphonso Mangoes',
  },
  {
    id: 'm4',
    truckId: 'TRK-119',
    name: 'TRK-119 • 5.1°C (LoRa Relay)',
    locationName: 'Nagpur East Corridor',
    temp: '5.1°C',
    status: 'Normal',
    xPercent: 66,
    yPercent: 38,
    shipmentId: 'SH-1055',
    cargoName: 'Mahabaleshwar Strawberries',
  },
];

export const mockRiskFactors: RiskFactor[] = [
  {
    factor: 'Temperature exposure',
    impact: '+12%',
    description: 'Brief temperature peak during automated defrost cycle (25 min @ 7.2°C).',
    type: 'negative',
  },
  {
    factor: 'Ethylene trend',
    impact: '+5%',
    description: 'Normal biological respiration level for mature fresh apples.',
    type: 'negative',
  },
  {
    factor: 'Humidity level',
    impact: '+4%',
    description: 'Maintained optimal 72% relative humidity in cargo chamber.',
    type: 'negative',
  },
  {
    factor: 'Transit duration',
    impact: '+2%',
    description: 'On schedule with 3h 15m remaining transit time.',
    type: 'negative',
  },
  {
    factor: 'Handling & door openings',
    impact: '0%',
    description: 'Zero unauthorized door openings or seal tampering detected.',
    type: 'neutral',
  },
];

export const mockJourneyStages: JourneyStage[] = [
  {
    step: 1,
    title: 'Farm Origin & Harvest',
    location: 'Solan Valley Orchards, HP',
    time: '02 Oct 2026, 06:00 AM',
    condition: 'Chilled at pickup: 3.8°C',
    verificationStatus: 'Verified',
    icon: 'farm',
  },
  {
    step: 2,
    title: 'Collection Center',
    location: 'Nashik Aggregation Hub',
    time: '02 Oct 2026, 02:30 PM',
    condition: 'Pre-cooling verified: 4.1°C',
    verificationStatus: 'Verified',
    icon: 'storage',
  },
  {
    step: 3,
    title: 'Cold Storage Vault',
    location: 'Nashik Cold Vault C-04',
    time: '03 Oct 2026, 08:00 AM',
    condition: 'Staged: 3.5°C, 80% RH',
    verificationStatus: 'Verified',
    icon: 'storage',
  },
  {
    step: 4,
    title: 'Reefer Truck Transit',
    location: 'Highway NH-44 → Raipur',
    time: '05 Oct 2026, 12:45 PM',
    condition: 'In Transit: 5.2°C (1 brief defrost peak resolved)',
    verificationStatus: 'Verified',
    icon: 'truck',
  },
  {
    step: 5,
    title: 'Wholesaler Warehouse',
    location: 'Raipur Regional Terminal Bay 04',
    time: 'Estimated Today 04:30 PM',
    condition: 'Approaching Dock • Safe to receive',
    verificationStatus: 'Pending',
    icon: 'warehouse',
  },
];

export const mockAlerts: AlertItem[] = [
  {
    id: 'alt-1',
    time: '18 minutes ago',
    truckId: 'TRK-112',
    shipmentId: 'SH-1042',
    problem: 'Truck TRK-112 has been offline for 18 minutes. Sensor data is being saved offline on the vehicle.',
    severity: 'Critical',
    category: 'Needs attention',
  },
  {
    id: 'alt-2',
    time: '42 minutes ago',
    truckId: 'TRK-108',
    shipmentId: 'SH-1031',
    problem: 'Temperature in TRK-108 has been above the recommended range (8.7°C vs max 6.0°C) for 42 minutes.',
    severity: 'Warning',
    category: 'Needs attention',
  },
  {
    id: 'alt-3',
    time: '1 hour ago',
    shipmentId: 'SH-1031',
    problem: 'Shipment SH-1031 has only 2.8 days of estimated shelf life remaining.',
    severity: 'Warning',
    category: 'Warnings',
  },
  {
    id: 'alt-4',
    time: '2 hours ago',
    truckId: 'TRK-104',
    shipmentId: 'SH-1024',
    problem: 'Shipment SH-1024 has successfully synchronized its offline data upon reaching long-range gateway.',
    severity: 'Info',
    category: 'Resolved',
    resolved: true,
  },
];

export const mockVerificationRecord: VerificationRecord = {
  shipmentId: 'SH-1024',
  batchesRecorded: 128,
  batchesVerified: 128,
  issuesFound: 0,
  integrityPercentage: 100,
  sampleTemperature: '5.2°C',
  sampleTimestamp: '05 Oct 2026, 04:15 PM',
  fingerprint: 'A73B91F82C4E9D021A8892BC',
  storedVerification: 'A73B91F82C4E9D021A8892BC',
  isMatch: true,
};

export const mockConnectionNodes: ConnectionNode[] = [
  {
    truckId: 'TRK-104',
    internetStatus: 'Connected',
    longRangeStatus: 'Connected',
    storedRecordsCount: 0,
  },
  {
    truckId: 'TRK-112',
    internetStatus: 'Unavailable',
    longRangeStatus: 'Offline',
    storedRecordsCount: 247,
  },
  {
    truckId: 'TRK-117',
    internetStatus: 'Unavailable',
    longRangeStatus: 'Relay Active',
    storedRecordsCount: 14,
    relayPath: 'TRK-117 → Long-range connection → TRK-119 → Internet → FreshTrace AI',
  },
];
